services:
  - type: web
    name: laravel-todo-list
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: APP_NAME
        value: Laravel Todo List
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DEMO_READ_ONLY
        value: false
      - key: APP_URL
        value: https://laravel-todo-list-awlf.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
